version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=ExcellentFreeTime
      - PROXY_DOMAIN=code.backlund.co
    volumes:
      - /home/peter/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
